export const brightspots = [
  {
    text: "Clean power is taking over — last year, wind and solar supplied 40% of the world’s electricity, the highest share ever",
    image: "/images/cleanenergy.png",
    source: "Ember",
    year: 2024,
  },
  {
    text: "The Amazon is catching its breath — deforestation has fallen by nearly a third since 2023",
    image: "/images/amazon-forest.png",
    source: "Brazil Gov / INPE",
    year: 2024,
  },
  {
    text: "The Iberian lynx, once down to just a handful, now numbers over 2,000 — no longer endangered",
    image: "/images/iberianlynx.png",
    source: "IUCN",
    year: 2024,
  },
  {
    text: "Two-thirds of the ocean just came under protection — the High Seas Treaty is finally in force",
    image: "/images/high-seas-treaty.png",
    source: "United Nations",
    year: 2025,
  },
  {
    text: "HIV is in retreat — new infections are down 40% since 2010, and AIDS deaths have been cut in half",
    image: "/images/hiv-progress.png",
    source: "UNAIDS",
    year: 2024,
  },
  {
    text: "Kids across Africa are lining up for the new malaria shot — and deaths are already starting to fall",
    image: "/images/malaria-vaccine.png",
    source: "WHO / Gavi",
    year: 2025,
  },
  {
    text: "Love wins in Thailand — marriage equality became law, and couples began tying the knot in 2025",
    image: "/images/thailand-equality.png",
    source: "AP",
    year: 2025,
  },
  {
    text: "Scientists finally cracked it — a fusion reactor made more power than it used. Twice",
    image: "/images/fusion-breakthrough.png",
    source: "DOE / NIF",
    year: 2024,
  },
  {
    text: "Starship flew, landed, and even tossed satellites into orbit — the dream of a fully reusable rocket is real",
    image: "/images/spacex-starship.png",
    source: "Reuters",
    year: 2025,
  },
  {
    text: "Electric cars blew past 1 in 5 new sales worldwide — the tipping point everyone was waiting for",
    image: "/images/ev-20percent.png",
    source: "IEA",
    year: 2025,
  },
  {
    text: "Life expectancy keeps climbing — more of us are living into our 70s and 80s than ever before",
    image: "/images/life-expectancy.png",
    source: "WHO",
    year: 2024,
  },
  {
    text: "Nepal doubled its wild tigers — something conservationists once said was impossible",
    image: "/images/nepal-tigers.png",
    source: "WWF / Nepal Gov",
    year: 2024,
  },
  {
    text: "The ozone hole over Antarctica just shrank to its smallest since the 1980s",
    image: "/images/ozone-hole.png",
    source: "NASA / WMO",
    year: 2025,
  },
];
