// utils/brightspotPool.ts
export const brightspots = [
  {
    text: "Clean energy is taking over — last year it supplied 40% of the world’s electricity, the highest share in history.",
    image: "/images/clean-power-40.png",
    source: "Ember",
    year: 2024,
  },
  {
    text: "Solar power is exploding — the world passed 2 terawatts in 2024, doubling in less than two years.",
    image: "/images/solar-2tw.png",
    source: "Global Solar Council",
    year: 2024,
  },
  {
    text: "In 2024, the world added nearly 600 gigawatts of solar — the biggest single-year jump ever.",
    image: "/images/solar-record-2024.png",
    source: "SolarPower Europe",
    year: 2024,
  },
  {
    text: "For the first time, Europe got more electricity from the sun than from coal.",
    image: "/images/eu-solar-beats-coal.png",
    source: "Ember",
    year: 2024,
  },
  {
    text: "The Amazon is breathing again — deforestation has fallen by nearly a third since 2023.",
    image: "/images/amazon-forest.png",
    source: "Brazil Gov / INPE",
    year: 2024,
  },
  {
    text: "A comeback story: the Iberian lynx, once nearly extinct, now numbers over 2,000 and is no longer endangered.",
    image: "/images/iberianlynx.png",
    source: "IUCN",
    year: 2024,
  },
  {
    text: "The world just agreed to protect two-thirds of the ocean — a new global treaty is now officially in action.",
    image: "/images/high-seas-treaty.png",
    source: "United Nations",
    year: 2025,
  },
  {
    text: "In Senegal, a disease that once blinded thousands has been wiped out for good.",
    image: "/images/trachoma-senegal.png",
    source: "WHO",
    year: 2025,
  },
  {
    text: "Chad has eliminated sleeping sickness, a deadly disease that plagued villages for generations.",
    image: "/images/sleeping-sickness-chad.png",
    source: "WHO",
    year: 2024,
  },
  {
    text: "Guinea worm, once infecting millions, is down to only a handful of cases worldwide — eradication is near.",
    image: "/images/guinea-worm.png",
    source: "The Carter Center",
    year: 2024,
  },
  {
    text: "Fewer children are dying than ever before — under-5 deaths hit a record low in the latest UN report.",
    image: "/images/under5-deaths.png",
    source: "UNICEF / WHO",
    year: 2024,
  },
  {
    text: "HIV is in retreat — new infections are down 40% since 2010, and AIDS deaths have been cut in half.",
    image: "/images/hiv-progress.png",
    source: "UNAIDS",
    year: 2024,
  },
  {
    text: "Across Africa, children are lining up for the first malaria vaccine — now rolling out in 23 countries.",
    image: "/images/malaria-vaccine-rollout.png",
    source: "WHO / Gavi",
    year: 2025,
  },
  {
    text: "Early results are promising — in Cameroon, districts using the new malaria vaccine are seeing fewer child deaths.",
    image: "/images/malaria-impact.png",
    source: "Gavi",
    year: 2025,
  },
  {
    text: "Doctors are using CRISPR to cure sickle-cell disease — patients who once lived in pain are now healthy.",
    image: "/images/crispr-sicklecell.png",
    source: "CUH / FDA",
    year: 2024,
  },
  {
    text: "Thailand just legalized same-sex marriage — couples began tying the knot in January 2025.",
    image: "/images/thailand-equality.png",
    source: "AP",
    year: 2025,
  },
  {
    text: "Liechtenstein’s marriage equality law came into effect in 2025 — another country joining the movement.",
    image: "/images/liechtenstein-equality.png",
    source: "Human Rights Campaign",
    year: 2025,
  },
  {
    text: "In July 2025, Saint Lucia decriminalized same-sex relations, joining a growing wave of change in the Caribbean.",
    image: "/images/saint-lucia-decrim.png",
    source: "AP",
    year: 2025,
  },
  {
    text: "Europe passed a landmark Nature Restoration Law in 2024, committing to revive 20% of land and sea by 2030.",
    image: "/images/eu-nature-restoration.png",
    source: "European Commission",
    year: 2024,
  },
  {
    text: "In 2024, the largest dam removal in U.S. history reopened the Klamath River — and salmon are already returning.",
    image: "/images/klamath-salmon.png",
    source: "NOAA / CDFW",
    year: 2024,
  },
];
